### ISSUE TITLE
Windows Server installation error

### ISSUE THREAD

**Issue by computer-logix** [franzinc/nfs#10]
I purchased a commercial license and sent a support message to info@franz.com but haven't received a response so I will try here.

When installing it on a Windows Server 2022 Standard machine the service won't start and it displays the following message during installation:

```
wait-for-service-to-start: Unexpected service state: 1
<The Lisp process exited with status 1 (0x1)>
```

I'm hoping it's just a missing prerequisite that isn't included in the the installer.
It was a fresh server install that is now in production, so I can't exactly experiment.   I would like to create NFS shares to make backing up easier and faster than over CIFS.

Has anyone else encountered this problem as well?

**Comment by layeratwork** [comment]
Just searched our email archives and found no hits with that error message.  Send email to support@franz.com and someone will help you.
